//
//  HomePresenter.swift
//  The News App
//
//  Created by Karim Cordilia on 21/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentNews(news: NewsViewModel)
}

class HomePresenter: HomePresentationLogic {
  weak var viewController: HomeDisplayLogic?
    
    func presentNews(news: NewsViewModel) {
        viewController?.displayNews(news: news)
    }
}
