//
//  HomeWorker.swift
//  The News App
//
//  Created by Karim Cordilia on 21/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    func getNews(completionHandler: @escaping (Result<News, Error>) -> Void) {
        let networkingManager = NetworkingManager()
        guard let url = URL(
            string: Endpoints.all.rawValue,
            relativeTo: APIConfig.baseURL)?
            .addQuery(
                HttpHeaders.apiToken.rawValue,
                value: APIConfig.apiKey
            )
            .addQuery(
                HttpHeaders.language.rawValue,
                value: APIConfig.language
            ) else { return }
        let request = URLRequest(url: url)
        networkingManager.request(url: request, completion: completionHandler)
    }
}
