//
//  HomeInteractor.swift
//  The News App
//
//  Created by Karim Cordilia on 21/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func loadNews()
}

protocol HomeDataStore {
    
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    
    func loadNews() {
        worker?.getNews { [weak self] result in
            switch result {
            case .success(let news):
                let newsViewModel = NewsViewModel(news: news.data)
                self?.presenter?.presentNews(news: newsViewModel)
            case .failure(let error):
                print(error)
            }
        }
    }
}
